### ISSUE TITLE
Needs to be /

### ISSUE THREAD

**Issue by ajijohn** [SWEEP-Inc/DocuSWEEP#1]
https://github.com/SWEEP-Inc/DocuSWEEP/blob/599cd432f17bf8b2f2c3a8bdb1236e3018317b97/my-website/docusaurus.config.js#L9

The site does not load properly (docs.sweep.run)

From the documentation - https://docusaurus.io/docs/docusaurus.config.js/

baseUrl#

Type: string
Base URL for your site. This can also be considered the path after the host. For example, /metro/ is the baseUrl of https://facebook.github.io/metro/. For URLs that have no path, the baseUrl should be set to /. This field is related to the url field.

docusaurus.config.js
module.exports = {
  baseUrl: '/',
};

**Comment by collindang88** [comment]
fixed
